- type: job
  id: Adjutant
  name: job-name-adjutant
  description: job-description-adjutant
  playTimeTracker: JobAdjutant
  requirements:
    - !type:AgeRequirement
      minAge: 22
    - !type:TraitsRequirement
      inverted: true
      traits:
        - Muted
  icon: "JobIconAdjutant"
  weight: -1000
  startingGear: AdjutantGear
  supervisors: job-supervisors-adjutant
  canBeAntag: false
  access:
  - Adjutant
  - Command
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  bonusSkillPoints: 8
  defaultSkills:
    Bureaucracy: 2
    Eva: 3
    Piloting: 3
    Weapons: 2

- type: startingGear
  id: AdjutantGear
  equipment:
    eyes: ClothingEyesHudCommand
    shoes: ClothingShoesBootsLaceup
    id: AdjutantPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    - RubberStampAdjutant

- type: chameleonOutfit
  id: AdjutantChameleonOutfit
  job: Adjutant
  hasMindShield: true
  equipment:
    eyes: ClothingEyesHudCommand
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterAdjutant
    neck: ClothingNeckScarfStripedBrown
    belt: ClothingBeltStorageWaistbag
    gloves: ClothingHandsGlovesColorBlack
    back: ClothingBackpackAdjutant
    head: ClothingHeadHatBeretAdjutant
