# No idea why it's in sci but we ball.
# Why is this one file?
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 18000  # 5 hrs
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  jobPreviewEntity: PlayerStationAiPreview
  applyTraits: false
  # WL-Skills-start
  defaultSkills:
    Bureaucracy: 4
    Eva: 3
    Piloting: 4
    MechPiloting: 3
    IT: 4
    Atmospherics: 4
    Construction: 4
    Electrical: 4
    Generators: 4
    Anatomy: 4
    Chemistry: 4
    Medicine: 4
    ComplexDevices: 4
    Science: 4
    Forensics: 4
    Combat: 4
    Weapons: 4
    Botany: 4
    Cooking: 4
    Mixology: 4
  # WL-Skills-end

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  applyTraits: false
